### ISSUE TITLE
Cleanup !match output

### ISSUE THREAD

**Issue by MazGrasl** [Taloth/Aoe4bot#4]
Atm it already simplifies for more than 2 teams. But 4v4 gets too crowded

**Comment by Taloth** [comment]
About this one, we currently do:

1v1: `Beastyqt #1 (C1, 1448 Elo) - Delhi [L] ==> Lipany <== [W] Leenock #3 (D3, 1368 Elo) - Abbasid, 20 hours ago`

2v2: `mYi.TheMista #9 (1931 Elo) - English, paphellas #85 (1661 Elo) - Mongols [W] ==> King of the Hill <== [L] bigboser #1355 (1328 Elo) - French, LaGastonnade #984 (1366 Elo) - Rus, 4 days ago`

4v4: `tmb8 #36 (1930 Elo) - English, MAKEINUz #321 (1557 Elo) - Mongols, 猥琐的小人物 #227 (1629 Elo) - HRE, 傻不拉几 #179 (1659 Elo) - Chinese [W] ==> Danube River <== [L] Jinmo #235 (1624 Elo) - HRE, airstrike900 #7 (2181 Elo) - Chinese, gubuk2006 #169 (1672 Elo) - English, bluesky9532 #6472 (1117 Elo) - Mongols, 1 day ago`

ffa: `mYi.TheMista [English] vs paphellas [Mongols] vs bigboser [French] vs LaGastonnade [Rus] on King of the Hill, 4 days ago`
It hides elo, it'll also not show [W] [L] for the winners and losers.
(This one isn't visible, coz there's no custom matches on the api)

What I'd suggest is to hide elo for 2v2/3v3/4v4 as well:
2v2: `mYi.TheMista [English], paphellas [Mongols] vs bigboser [French], LaGastonnade [Rus] on King of the Hill, 4 days ago`
4v4: `tmb8 [English], MAKEINUz [Mongols], 猥琐的小人物 [HRE], 傻不拉几 [Chinese] vs Jinmo [HRE], airstrike900 [Chinese], gubuk2006 [English], bluesky9532 [Mongols] on Danube River, 1 day ago`

or

2v2: `mYi.TheMista [English], paphellas [Mongols] ==> King of the Hill <==  bigboser [French], LaGastonnade [Rus], 4 days ago`
4v4: `tmb8 [English], MAKEINUz [Mongols], 猥琐的小人物 [HRE], 傻不拉几 [Chinese] ==> Danube River <== Jinmo [HRE], airstrike900 [Chinese], gubuk2006 [English], bluesky9532 [Mongols], 1 day ago`

Rationale is that the elo adds so much to the output, and is less relevant. 
I think we can still show [W]/[L] when there are 2 teams amd we use the second format.

What do you think?

**Comment by MazGrasl** [comment]
Agreed, ELO is not really important in 4v4 anyway.
I've thought about shortening the civs as well to 3 letters each.

**Comment by Taloth** [comment]
> I've thought about shortening the civs as well to 3 letters each.

I had that in the original version, but I reverted it because I felt it'd likely be confusing to casual watchers. "What does MON mean?" would invariably be the follow up question.
I already shortened the main ones: HRE, Delhi, Abbasid. 
That said, I'm not opposed to it, but there's a tradeoff there.

**Comment by MazGrasl** [comment]
Makes sense, as long as we don't run into the 400 character limit it's not a big issue anyway.
That said, I kinda prefer the second format - in the first one, the "vs" is very hard to spot.
